### ISSUE TITLE
References and examples

### ISSUE THREAD

**Issue by weijianzhg** [jpfairbanks/GraphMatrices.jl#2]
Hi @jpfairbanks,

 Could you provide some references and examples for this package? 

Thanks,
Weijian

**Comment by ashkan-leo** [comment]
I would like to see some examples as well. I don't know how to use any function in the package.

**Comment by jpfairbanks** [comment]
This package has been integrated into LightGraphs.jl. You can access the various GraphMatrices using their names NormalizedLaplacian(g) etc.
