### ISSUE TITLE
JuliaGraphs?

### ISSUE THREAD

**Issue by sbromberger** [jpfairbanks/GraphMatrices.jl#3]
Would you consider putting this package under the JuliaGraphs organization?

**Comment by jpfairbanks** [comment]
Yes can you make me a member?

**Comment by sbromberger** [comment]
Done. (I also transferred LightGraphs in there so that we've got a common place to discuss cool graph things.)

**Comment by sbromberger** [comment]
Did you want to move this over to the organization?

**Comment by jpfairbanks** [comment]
If you think that will improve visibility then it is probably a good thing. How do I do that?

**Comment by sbromberger** [comment]
Go to the repo page, click "settings", scroll down, transfer ownership to JuliaGraphs. (You're a member there so you have write/push access to all repos.)

**Comment by sbromberger** [comment]
Now that we've got integration, it might make sense to move the repo and then get it published. What do you think?

**Comment by hayd** [comment]
bump!

**Comment by jpfairbanks** [comment]
It is tagged and published. Is anyone planning to work on this? I have added one new feature to master that is not yet tagged but haven't written docs for it yet. it is PunchedMatrix which allows you to compute the fiedler vector as the extremal eigenvector, if somebody wants to use that I can tag a new release.

**Comment by sbromberger** [comment]
@jpfairbanks is this package more or less complete? If so, perhaps you'd consider moving it over to JuliaGraphs?
